#                                                                        #
# Default subroutes configuration for the Blog package                   #
#                                                                        #

-
  name: 'Blog post comment creation'
  uriPattern:    'typo3/plugin/blog/comments/create'
  defaults:
    '@package':    'TYPO3.Plugin.Blog'
    '@controller': 'Comment'
    '@format': 'html'
    '@action': 'create'
